In [1]:
from keras import models
from keras import layers
from keras import optimizers, losses, metrics

import numpy as np

Using TensorFlow backend.


<br>
<br>

# 데이터 생성

In [2]:
# 캐릭터 글자 목록
char_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 
             'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

# 캐릭터 사전 생성
char_to_idx = {c: i for i, c in enumerate(char_list)}
dic_len = len(char_to_idx)

print(char_to_idx)


{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}


In [3]:
# 단어 목록
# 앞의 세 글자가 주어지면 마지막 글자를 예측
# lov -> e
word_list = ['love', 'look', 'face', 'fast', 'home', 'hope',
             'good', 'gold', 'tree', 'true', 'road', 'rock']

In [4]:
# 배치 데이터 생성
def make_batch(word_list):
    
    input_batch = []
    target_batch = []

    for word in word_list:
        # 입력 단어를 인덱스로 변환
        input = [char_to_idx[c] for c in word[:-1]]
        
        # 목표 캐릭터를 인덱스로 변환
        target = char_to_idx[word[-1]]

        # 입력 인덱스를 원핫인코딩으로 변환
        input_batch.append(np.eye(dic_len)[input])

        # 목표 인덱스를 원핫인코딩으로 변환
        target_batch.append(np.eye(dic_len)[target])

    return np.array(input_batch), np.array(target_batch)

In [5]:
# 입력/목표 배치 생성
x_train, y_train = make_batch(word_list)

In [6]:
x_train[0]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [7]:
y_train[0]


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

<br>
<br>

# 모델 생성

In [8]:
# 세 글자만큼 타임스텝 반복
time_step = 3

def build_model():
    
    model = models.Sequential()
    model.add(layers.LSTM(64, input_shape = (time_step, dic_len)))
    model.add(layers.Dense(dic_len, activation='softmax'))

    model.compile(optimizer='rmsprop',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    
    return model              

<br>
<br>

# 훈련 및 테스트

In [9]:
# 모델 생성
model = build_model()

# 훈련 시작
model.fit(x_train,
          y_train,
          epochs=100,
          batch_size=1)


Epoch 1/100
12/12 [==============================] - 1s 47ms/step - loss: 3.2398 - acc: 0.0833
Epoch 2/100
12/12 [==============================] - 0s 6ms/step - loss: 3.1561 - acc: 0.4167
Epoch 3/100
12/12 [==============================] - 0s 6ms/step - loss: 3.0804 - acc: 0.5000
Epoch 4/100
12/12 [==============================] - 0s 6ms/step - loss: 2.9902 - acc: 0.6667
Epoch 5/100
12/12 [==============================] - 0s 6ms/step - loss: 2.8739 - acc: 0.6667
Epoch 6/100
12/12 [==============================] - 0s 6ms/step - loss: 2.7218 - acc: 0.6667
Epoch 7/100
12/12 [==============================] - 0s 7ms/step - loss: 2.5181 - acc: 0.5833
Epoch 8/100
12/12 [==============================] - 0s 6ms/step - loss: 2.2526 - acc: 0.5833
Epoch 9/100
12/12 [==============================] - 0s 6ms/step - loss: 1.9450 - acc: 0.5000
Epoch 10/100
12/12 [==============================] - 0s 6ms/step - loss: 1.6510 - acc: 0.5000
Epoch 11/100
12/12 [==============================] - 0s 6

12/12 [==============================] - 0s 6ms/step - loss: 0.0639 - acc: 1.0000
Epoch 88/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0628 - acc: 1.0000
Epoch 89/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0580 - acc: 1.0000
Epoch 90/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0579 - acc: 1.0000
Epoch 91/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0513 - acc: 1.0000
Epoch 92/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0521 - acc: 1.0000
Epoch 93/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0469 - acc: 1.0000
Epoch 94/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0461 - acc: 1.0000
Epoch 95/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0426 - acc: 1.0000
Epoch 96/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0420 - acc: 1.0000
Epoch 97/100
12/12 [==============================] - 0s 6ms/st

In [10]:
# 훈련셋 데이터 예측
# 26개 캐릭터의 원핫인코딩 형식
results = model.predict(x_train)
results


array([[2.15593610e-09, 3.92362542e-09, 3.39198358e-09, 5.97915961e-04,
        9.74902153e-01, 2.03824646e-09, 2.68940803e-09, 2.76509993e-09,
        1.57705782e-09, 2.68146860e-09, 2.40238272e-02, 2.29818409e-09,
        3.51762530e-09, 4.13557588e-09, 6.52650778e-09, 3.00624303e-09,
        2.36155895e-09, 1.50774948e-09, 4.24983693e-09, 4.76046873e-04,
        1.38333534e-09, 2.31604114e-09, 2.56572252e-09, 1.82073034e-09,
        3.97753119e-09, 8.84318618e-10],
       [7.46743201e-09, 1.86082794e-08, 2.81349610e-08, 1.10401930e-02,
        4.24866937e-02, 8.58319904e-09, 2.28888357e-08, 2.38146090e-08,
        1.19482735e-08, 3.02524192e-08, 9.45788741e-01, 2.35798030e-08,
        1.80306721e-08, 1.87187030e-08, 2.95103924e-08, 2.82794712e-08,
        1.89037674e-08, 1.26891386e-08, 1.86165874e-08, 6.84256607e-04,
        1.20268808e-08, 1.85807583e-08, 1.90239273e-08, 1.24103821e-08,
        2.17478977e-08, 1.80600992e-08],
       [2.60268482e-08, 5.58085418e-08, 4.70681627e-08

In [11]:
# 1축을 기준으로 최대값의 인덱스 구함
results = np.argmax(results, 1) 
results


array([ 4, 10,  4, 19,  4,  4,  3,  3,  4,  4,  3, 10], dtype=int64)

In [12]:
# 예측 결과 출력
for i, word in enumerate(word_list):
    last_char = char_list[results[i]]
    print(word[:3] + ' -> ' + word[:3] + last_char)
    

lov -> love
loo -> look
fac -> face
fas -> fast
hom -> home
hop -> hope
goo -> good
gol -> gold
tre -> tree
tru -> true
roa -> road
roc -> rock
